### ISSUE TITLE
Fill in and/or surface historical payment records

### ISSUE THREAD

**Issue by bjpatterson** [BallStateCBER/cri#49]
## Description:
Currently, some of the original communities have been advanced to the leadership survey, with the payment checkbox marked as complete, but no corresponding payment shows up on the Payment Records page.  (Delphi is one such offending community, for example.)

## Potential Tasks:
- [x] If payment records don't exist, retroactively create them (most/all should be OCRA-funded).
- [x] Make sure these payments surface on the Payment Records page.
- [x] defDone: Every CRI survey/presentation has a corresponding Payment Record.

**Comment by PhantomWatson** [comment]
Turns out some payment records were added by a user account that was added sometime before February of 2016 and since deleted, and a bug was preventing any payment records from being shown if they had such details missing.

Now, all payment records should show up regardless of what details are missing.

**Comment by bjpatterson** [comment]
Does this mean the issue is resolved, or might there still be missing records that were never input in the first place?

**Comment by PhantomWatson** [comment]
Not fully resolved yet. I'm going to check through the database and look for any Step 2+ communities without payment records.

**Comment by PhantomWatson** [comment]
I've confirmed that there aren't any advanced communities with missing payment records.
